---
abstract: 'CGI::Plus -- Extra utilities for CGI'
author:
    - "Miko O'Sullivan <miko@idocs.com>"
generated_by: home grown
license: perl
name: CGI-Plus
provides:
    CGI::Plus:
        file: lib/CGI/Plus.pm
        version: 0.14
requires:
    CGI::Cookie: 0
    CGI::Safe: 0
    String::Util: 0
    Test: 0
    perl: 5.003
version: 0.14
